universe = docker
docker_image = pangyuteng/ml:latest

executable = viz.sh
transfer_input_files = viz.sh,viz_utils.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

log = log/viz.$(cluster).$(process).log
error = log/viz.$(cluster).$(process).err
output = log/viz.$(cluster).$(process).out

requirements = (OpSys == "LINUX" && Arch == "X86_64")
request_cpus = 1
request_memory = 5GB
request_disk = 5GB

max_materialize = 10
arguments = "$(myargs)"
queue myargs from viz.args
