FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
    autotools-dev \
    build-essential \
    ca-certificates \
    software-properties-common \
    vim git wget curl \
    make \
    cmake 