FROM acilbwh/chestimagingplatform:latest

# "nothing to see here please move along"
# maybe non-root will be able to access...
RUN chmod 777 -R /root/miniconda2
RUN chmod 777 -R /ChestImagingPlatform-build/CIP-build
